"""add book owner and public flag, user admin flag

Revision ID: 7af4d56d2e00
Revises: 58e710ff6a72
Create Date: 2026-07-22 01:04:42.166752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7af4d56d2e00'
down_revision: Union[str, Sequence[str], None] = '58e710ff6a72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('owner_id', sa.Integer(), nullable=False))
    op.add_column('books', sa.Column('is_public', sa.Boolean(), server_default='false', nullable=False))
    op.create_foreign_key(None, 'books', 'users', ['owner_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'books', type_='foreignkey')
    op.drop_column('books', 'is_public')
    op.drop_column('books', 'owner_id')
    # ### end Alembic commands ###
